---

name: Build project

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: SekiroFpsUnlockAndMore
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Restore the application
      run: msbuild "$env:Solution_Name.sln" /t:Restore /p:Configuration=$env:Configuration

    - name: Create the app package
      run: msbuild "$env:Solution_Name.sln" /p:Configuration=$env:Configuration

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.Solution_Name }}
        path: ${{ env.Solution_Name }}/bin/x64/Release/${{ env.Solution_Name }}.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        fail_on_unmatched_files: true
        make_latest: true
        files: |
          ${{ env.Solution_Name }}/bin/x64/Release/${{ env.Solution_Name }}.exe
